//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriendshipFinder.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GerardJennyEntities : DbContext
    {
        public GerardJennyEntities()
            : base("name=GerardJennyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostComment> PostComments { get; set; }
        public virtual DbSet<PostDislike> PostDislikes { get; set; }
        public virtual DbSet<PostLike> PostLikes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Writing> Writings { get; set; }
    }
}
